addons:
  ssh_known_hosts:
  - 46.101.136.26
  apt:
    packages:
    - sshpass
language: node_js
node_js:
- '4.1'
branches:
  only:
  - release
install: npm install
before_script:
- mysql -u root < ./database/schema.sql
- npm install -g mocha
after_success:
- mkdir build
- mv * build
- tar -czf package.tgz build
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no package.tgz root@46.101.136.26:/home/kysiek/AHWarehouse
- sshpass -e ssh root@46.101.136.26 /home/kysiek/AHWarehouse/deploy.sh
dd:
  secure: Wuti/MbZKATyMyyjHqDTuTi2LLFM09jtgIpWnfVveHxXN3z6D0jogc8xXQdjT4ttPhhhwTF4RCftcLU2M7hToCFPMbaNz4xRNclQG+SM2cc/pehQuBdOY9k7/mtgar8033bpNLL8GeXv0GmN65xDPyl8k5CuBVzG0iHL2jzuEfvQmm+zBjPlIexqr9ObKJEI4U0ifiFgp1HuaR2fJfiv98xCCVr1OX+3LB3r10y5UEMOILGMndL3uO4K2rNMSrwxsu7yqwKLgIhhoktHXb9hNqHlWYy0cxZmTXZFXQZxTZXHFzVaI193TSwTwSDvwvLghBqpKVjnHtI4ZGumuBw7LK1m30YgTz45jirsZaMONPf6GodV/0ATxJmRuJLLO5t9XeTLaKdHX7v4GSASxEPULA1u9TEsutigw7p/fc3RlvfjE2vAKuySyQ3gFIjcTlRJptlsGWE6FiHGoA5BZE8MuSlptBGZC5VHZCKSBKQzAJM1RKUNzQMKrG5S9sDVeIBxZ3hIDUyg6kxjifipHYYrRlW6h8wy7zp9Bnb+wRkxelVZysfeApeIyJuwxbNZx7xnSKAPYkWt5h3GoJlQDpxDuSYrX7t8uzNGUdkxYvJK6kFJGGESzprMAWK10mdqKW4JnkWn4rsxoWxMMFTgW+uiLCrSJZ5Vb45EYoh6oJqXlCs=
