-- MySQL Script generated by MySQL Workbench
-- 11/16/15 18:00:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AHWarehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AHWarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AHWarehouse` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AHWarehouse` ;

-- -----------------------------------------------------
-- Table `AHWarehouse`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AHWarehouse`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  `authenticationToken` VARCHAR(255) NOT NULL,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AHWarehouse`.`DirectoryType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AHWarehouse`.`DirectoryType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AHWarehouse`.`Directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AHWarehouse`.`Directory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `rootPath` VARCHAR(1000) NULL,
  `directoryTypeId` INT NOT NULL,
  `ownerUserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_directory_directoryType_idx` (`directoryTypeId` ASC),
  INDEX `FK_directory_user_idx` (`ownerUserId` ASC),
  CONSTRAINT `FK_directory_directoryType`
    FOREIGN KEY (`directoryTypeId`)
    REFERENCES `AHWarehouse`.`DirectoryType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_directory_user`
    FOREIGN KEY (`ownerUserId`)
    REFERENCES `AHWarehouse`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AHWarehouse`.`AccessToDirectory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AHWarehouse`.`AccessToDirectory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `directoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Access_user_idx` (`userId` ASC),
  INDEX `FK_Access_Directory_idx` (`directoryId` ASC),
  CONSTRAINT `FK_Access_user`
    FOREIGN KEY (`userId`)
    REFERENCES `AHWarehouse`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Access_Directory`
    FOREIGN KEY (`directoryId`)
    REFERENCES `AHWarehouse`.`Directory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AHWarehouse`.`Resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AHWarehouse`.`Resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ownerUserId` INT NOT NULL,
  `directoryId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `locationOnServer` VARCHAR(255) NOT NULL,
  `mimetype` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
